In [ ]:
import numpy as np
dir(np)


In [265]:
a=np.array([1,2,3],dtype="int")
print(a)

[1 2 3]


In [19]:
a.shape

(3,)

In [21]:
a.ndim


1

In [268]:
a[1]=10
print(a)

[ 1 10  3]


In [70]:
e=np.array([[1,2,3],[3,4,5]])
print(e)

[[1 2 3]
 [3 4 5]]


In [71]:
e.shape

(2, 3)

In [72]:
e.ndim

2

In [256]:
b=np.arange(10,25,2)
print(b)

[10 12 14 16 18 20 22 24]


In [261]:
x=b.reshape(2,4)
print(x)

[[10 12 14 16]
 [18 20 22 24]]


In [262]:
x.shape

(2, 4)

In [263]:
x=b.reshape(2,2,2)
print(x)

[[[10 12]
  [14 16]]

 [[18 20]
  [22 24]]]


In [264]:
x.shape

(2, 2, 2)

In [65]:
type(x)

numpy.ndarray

In [37]:
c=np.full((3,3),6)
print(c)

[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [45]:
c.flatten()

array([6, 6, 6, 6, 6, 6, 6, 6, 6])

In [64]:
np.zeros((4,4),dtype="int")

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [249]:
8*np.random.random((4,4))+2
#x*np.random.random()+y
#y:-Start range from y
#x:-Till x+y range

array([[9.1401696 , 4.85843462, 2.94628241, 2.69826127],
       [6.09217905, 3.7845409 , 9.75429011, 9.90253744],
       [6.81247879, 6.14228599, 7.6331274 , 9.59964575],
       [4.59260894, 9.83062062, 5.16448191, 3.36913631]])

In [253]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [122]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [117]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [101]:
%timeit [ i**1 for i in range(1000)]

411 µs ± 4.32 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
